package main

// Manufacturer constants
const TYPE_MANU_PRODUCT = "PRODUCT"
const TYPE_MANU_STOCK = "MANU_STOCK"
const TYPE_DIST_STOCK = "DIST_STOCK"
const TYPE_RETL_STOCK = "RETL_STOCK"

// Trail constants
const TYPE_DELIVERY_SKU = "DELIVERY_SKU"
const TYPE_DELIVERY_MANU_OUT = "DELIVERY_MANU_OUT"
const TYPE_DELIVERY_DIST_IN = "DELIVERY_DIST_IN"
const TYPE_DELIVERY_DIST_OUT = "DELIVERY_DIST_OUT"
const TYPE_DELIVERY_RETL_IN = "DELIVERY_RETL_IN"
const TYPE_DELIVERY_RETL_OUT = "DELIVERY_RETL_OUT"
const TYPE_DELIVERY_TRAIL = "DELIVERY_TRAIL"
const TYPE_TX_LOG = "TX_LOG"
